### ISSUE TITLE
make subnet.k8s optional

### ISSUE THREAD

**Issue by ghost** [gravitational/terraform-gravity#6]
Hi,

I spent some time trying to implement the following configuration:

- create a new VPC with public and private network
- create a telekube cluster in the private network.
- register the cluster in an existing opscenter located in different VPC.

It seems like such configuration is currently not supported by gravitational/terraform-gravity because 
1. subnet.k8s is hardcoded, i.e. gravitational/terraform-gravity will always put clusters to a new separate subnet.
This is very suitable if there are several clusters in the same VPC.
However such subnet is rather redundant if each cluster works in its own VPC.

2. All servers in k8s.subnet are supposed to have public IP addresses. The current implementation doesn't support private networks
https://github.com/gravitational/terraform-gravity/blob/master/aws/network.tf#L29

I want to propose removing network.tf from the module and making k8s.subnet optional.
Instead of specifying subnet IP ranges, we could pass subnet_IDs of already created subnets to the telekube module.

For the 'one cluster, one VPC' scenario, that would be the IDs of VPC private subnets.
For the 'one VPC, many clusters' scenario, that could be new k8s subnets.

module "telekube" {
  ..
  subnet_ids = ["${aws_subnet.k8s.*.id}"]
  //subnet_ids = ["${aws_subnet.private.*.id}"]

Although it creates some additional overhead because terraform configuration for k8s have to be specified.
However I think it makes the module more flexible because it allows creating the cluster in any existing pre-configured subnet (public or private).

**Comment by knisbet** [comment]
@alexdudko I believe I've adopted most of this now in #7.

I've removed most networking (except for the internet gateway) from the vpc module, and split it into a networking module. The idea is, that you wouldn't use the network module from this repo, but replace it to you're own standard, and passing fields to the aws module. 

Keep in mind though, you do need to be a bit careful with the labels assigned to subnets, as kubernetes uses them as part of the kubernetes integrations.
