### ISSUE TITLE
security groups

### ISSUE THREAD

**Issue by ghost** [gravitational/terraform-gravity#8]
There is not way currently to add additional security groups to the instances as well as there is no way to change the security group created by terraform-gravity.

The default security group that terraform-gravity creates [allows access to port 22 from 0.0.0.0/0](https://github.com/gravitational/terraform-gravity/blob/master/aws/security_group.tf#L7) which is not appropriate configuration for production environments.

We need either to expose the security group and ASG launch configuration via outputs so that it would be possible to adjust them, or to make it possible passing a list of pre-created security groups as a variable.

**Comment by knisbet** [comment]
@alexdudko please take a look at the latest modifications to #7 

I've moved all the networking / security groups into their own module, which in you're environment you wouldn't use, but replace to you're own standard.
