### ISSUE TITLE
migration from gravitational/provisioner to gravitational/terraform-gravity

### ISSUE THREAD

**Issue by ghost** [gravitational/terraform-gravity#9]
@knisbet, we discussed that a possible way to migrate existing clusters created using gravitational/provisioner to gravitational/terraform-gravity could be to use gravitational/terraform-gravity to instance a new cluster with the same name as an existing cluster into the same VPC.

While I believe it is a great idea, it doesn't look like this path is available now because although  gravitational/terraform-gravity can use the same VPC, it will create completely new security groups, subnetworks and ACLs. By default old and new clusters will not even be able to communicate with each other. Also all existing security groups and network ACLs will need to be adjusted to be able to send traffic to and receive it from the new cluster. At the moment it looks more like a swap than a migration.

I know I've already touched this topic at https://github.com/gravitational/terraform-gravity/issues/6 but I really think the module should provide a way to install gravity into existing infrastructure (i.e. to use existing subnet IDs, security groups IDs and etc).

The module already allows to install a new cluster to existing VPC by passing ID of an existing VPC.
Existing security groups, existing subnetworks and network ACLs are not any different from that perspective. They can be already in place, they can already have a lot of external rules attached to them and creating additional rules for new subnetworks and new security groups is not a trivial task.

What do you think about moving security groups and networks definitions to their own submodules and using the same approach you used for VPC?

**Comment by knisbet** [comment]
I haven't attempted to test this out. I think the changes I currently have in #7 are better prepared for this.

We'll need to be careful though, because we're not really creating a new cluster in the same VPC, but using nodes managed by this module to extend, and eventually replace all the nodes in an existing cluster.
